version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="movies-db"
    ports:
      - 27017:27017
  test-db:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="movies-db"
    ports:
      - 27018:27017
    volumes:
      - type: tmpfs
        target: /data/db
